---
- name: Check is ssh installed
  ignore_errors: yes
  changed_when: false
  shell: command -v ssh -V 2>&1
  register: check_ssh_version

- name: Check is google chrome installed
  ignore_errors: yes
  changed_when: false
  shell: "command -v google-chrome-stable -version"
  register: check_chrome_version

- name: Chech is visual studio code installed
  ignore_errors: yes
  changed_when: false
  shell: "command -v code --version"
  register: check_vscode_version

- name: Check is ansible installed
  changed_when: false
  ignore_errors: yes
  shell: "command -v ansible --version"
  register: check_ansible_version

- name: Check is virtualbox installed
  changed_when: false
  ignore_errors: yes
  shell: "command -v VBoxManage --version"
  register: check_vbox_version

- name: Check is enpass installed
  stat:
    path: /opt/enpass/Enpasss
  register: check_enpass

- name: Check is docker installed
  changed_when: false
  ignore_errors: yes
  shell: "command -v docker --version"
  register: check_docker_version
  
### set_facts

- name: Enpass
  set_fact:
    fact_ssh_version: "{{ check_ssh_version.stdout }}"
    fact_google_chrome_version: "{{ check_chrome_version.stdout }}"
    fact_vscode_version: "{{ check_vscode_version.stdout }}"
    fact_ansible_version: "{{ check_ansible_version.stdout }}"
    fact_vbox_version: "{{ check_vbox_version.stdout }}"
    fact_enppas_instlled: "{{ check_enpass.stat.exists }}"
    fact_docker_version: "{{ check_docker_version.stdout }}"

### PRINTING

- name: SSH version
  debug:
    msg: "SSH Version: {{ fact_ssh_version }}"

- name: Google Chrome version
  debug:
    msg: "Google Chrome Version: {{ fact_google_chrome_version }}"

- name: Visual Studio Code version
  debug:
    msg: "Visual Studio Code Version: {{ fact_vscode_version }}"
  
- name: Ansible Version
  debug:
    msg: "Ansible Version: {{ fact_ansible_version }}"

- name: VirtualBox Version
  debug:
    msg: "VirtualBox Version: {{ fact_vbox_version }}"

- name: Docker Version
  debug:
    msg: "Docker Version: {{ fact_docker_version }}"
