---
- name: Extra grather facts
  include_tasks: extra_gather_facts.yml

- name: Configure sudo
  include_tasks: configure_sudo.yml

- name: Configure ssh
  include_tasks: configure_ssh.yml

- name: Install Google chrome
  include_tasks: install_google_chrome.yml
  when: fact_google_chrome_version is defined and fact_google_chrome_version == ""