- name: Copy private ssh key
  copy:
    content: "{{ userattr.ssh.private_key }}"
    dest: ~/.ssh/id_rsa
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600

- name: Copy public ssh key
  copy:
    content: "{{ userattr.ssh.public_key }}"
    dest: ~/.ssh/id_rsa.pub
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644