- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
  notify: Restart system