---
- name: Add an Apt signing key to helm
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add repository helm
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm
  
- name: Update the repository cache and install helm
  apt:
    name: helm
    state: latest
    update_cache: yes
