---
- name: update and upgrade
  apt:
    upgrade: dist
    update_cache: yes

- name: Install tools
  apt:
    pkg:
    - apt-transport-https
    - git
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    - findutils
    - pinta
    - python-setuptools

- name: Install pip3
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - paramiko
