---
- name: Add an Apt signing key to Visual Studio Code
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add repository Visual Studio Code
  apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
  
- name: Update the repository cache and install Visual Studio Code
  apt:
    name: code
    state: latest
    update_cache: yes
