---
- name: Add an Apt signing key to enpass
  apt_key:
    url: https://apt.enpass.io/keys/enpass-linux.key
    state: present

- name: Add repository enpass
  apt_repository:
    repo: deb https://apt.enpass.io/ stable main
    state: present
    filename: enpass
  
- name: Update the repository cache and install enpass
  apt:
    name: enpass
    state: latest
    update_cache: yes
