---
- name: Add an Apt signing key to google chrome
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub 
    state: present

- name: Add repository google chrome
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  
- name: Update the repository cache and install google-chrome
  apt:
    name: google-chrome-stable
    state: latest
    update_cache: yes
