---
- name: Clean
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io 
      - containerd
      - runc
    state: absent

- name: Add an Apt signing key to docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker
  
- name: Update the repository cache and install docker
  apt:
    pkg:
    - docker-ce 
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: yes
