---
- name: update and upgrade
  apt:
    upgrade: dist
    update_cache: yes

- name: Install tools
  apt:
    pkg:
    - apt-transport-https
    - git
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip