---
- name: Preparation of OS
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
  
    - include_role: 
        name: Ansible.Workstation.Configuration.Role.ConfigureProfile
      vars:
        input_role_vscode_extensions: "{{ inventory_group_all_user_profile.vscode.extenssions }}"
      loop_control:
        loop_var: input_role_user_atrr
      loop: "{{ lookup('dict', inventory_group_all_users) }}"
      when: input_role_user_atrr.key != "none"