---
- name: Preparation of OS
  hosts: all
  become: yes
  gather_facts: yes

  roles: 
    - role: Ansible.Workstation.Configuration.Role.PreparationOs
    - role: Ansible.Workstation.Configuration.Role.ConfigureProfile